## **Task 1: Identifying the Prediction Target**

In [2]:
import pandas as pd
df = pd.read_csv("bank-additional.csv", sep=';')
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,30,blue-collar,married,basic.9y,no,yes,no,cellular,may,fri,...,2,999,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1,no
1,39,services,single,high.school,no,no,no,telephone,may,fri,...,4,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no
2,25,services,married,high.school,no,yes,no,telephone,jun,wed,...,1,999,0,nonexistent,1.4,94.465,-41.8,4.962,5228.1,no
3,38,services,married,basic.9y,no,unknown,unknown,telephone,jun,fri,...,3,999,0,nonexistent,1.4,94.465,-41.8,4.959,5228.1,no
4,47,admin.,married,university.degree,no,yes,no,cellular,nov,mon,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.191,5195.8,no

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4119 entries, 0 to 4118
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             4119 non-null   int64
 1   job             4119 non-null   str
 2   marital         4119 non-null   str
 3   education       4119 non-null   str
 4   default         4119 non-null   str
 5   housing         4119 non-null   str
 6   loan            4119 non-null   str
 7   contact         4119 non-null   str
 8   month           4119 non-null   str
 9   day_of_week     4119 non-null   str
 10  duration        4119 non-null   int64
 11  campaign        4119 non-null   int64
 12  pdays           4119 non-null   int64
 13  previous        4119 non-null   int64
 14  poutcome        4119 non-null   str
 15  emp.var.rate    4119 non-null   float64
 16  cons.price.idx  4119 non-null   float64
 17  cons.conf.idx   4119 non-null   float64
 18  euribor3m       4119 non-null   float64
 19  nr.employed     4119 non-null   float64
 20  y               4119 non-null   str
dtypes: float64(5), int64(5), str(11)
memory usage: 675.9 KB

In [4]:
df.shape

(4119, 21)

In [11]:
df[['y', 'poutcome', 'default']].describe()

           y     poutcome default
count   4119         4119    4119
unique     2            3       3
top       no  nonexistent      no
freq    3668         3523    3315

In [15]:
X = df.drop("y", axis=1)
y = df["y"]

The target variable is y, as it indicates whether the client subscribed to the term deposit (yes/no). This directly reflects the success of the marketing campaign, making it the appropriate prediction objective.

A potential alternative could be poutcome, but this represents the outcome of a previous campaign, not the current one. It is therefore a historical feature rather than the target.

Another possible option is default, since it is categorical. However, it relates to credit risk and not to the marketing campaign outcome. Using it would change the problem.